<?php

declare(strict_types=1);

namespace Civi\Dfc\Test\Security;

use Civi\Dfc\V2\Identity\DfcReleaseConfig;
use Civi\Dfc\V2\Security\AccessTokenValidator;
use Civi\Dfc\V2\Security\BearerAuthenticator;
use Civi\Dfc\V2\Security\BearerTokenExtractor;
use Civi\Dfc\V2\Security\JwksCache;
use Civi\Dfc\V2\Security\JwksDocument;
use Civi\Dfc\V2\Security\JwksFetcherInterface;
use Civi\Dfc\V2\Security\LocalJwtDecoder;
use Civi\Dfc\V2\Security\OidcClientConfig;
use Civi\Dfc\V2\Security\OidcEndpoints;
use Civi\Dfc\V2\Security\ScopePermissionRegistry;
use Civi\Dfc\V2\Security\JwksUnavailableException;

/**
 * Wires a complete, network-free OIDC resource server for the tests.
 *
 * NOT A TEST CLASS — the file name does not end in `Test.php`.
 *
 * ============================================================================
 * WHAT THIS EXISTS TO PROVE
 * ============================================================================
 * That the whole chain is hermetic. Every collaborator here is local: the key
 * material is generated by {@see JwtFactory}, the "issuer" key set comes from a
 * scripted fetcher, and the clock is {@see TestClock}. There is no HTTP client, no
 * sleep and no external repository anywhere in the OIDC unit suite.
 *
 * That matters because the alternative — asserting token behaviour against the live
 * DFC realm — needs a client credential this project does not have (BLK-014 records
 * that no confidential client with a service account is available), and would be a
 * test that fails when somebody's network does.
 *
 * ============================================================================
 * THE SCRIPTED FETCHER IS THE INTERESTING PART
 * ============================================================================
 * {@see ScriptedJwksFetcher} hands out a different key set on each call, which is how
 * "unknown `kid` triggers exactly one refresh and then succeeds" and "still unknown
 * after the refresh fails" are both expressible without a rotating IdP. It also counts
 * its calls, so a test can assert the cache did NOT go to the network — which is the
 * load-protection claim {@see JwksCache} makes.
 *
 * @package Civi\Dfc
 */
final class OidcHarness
{
    public readonly TestClock $clock;

    public readonly ScriptedJwksFetcher $fetcher;

    public readonly JwksCache $jwks;

    public readonly OidcEndpoints $endpoints;

    public readonly OidcClientConfig $config;

    public readonly AccessTokenValidator $validator;

    public readonly BearerTokenExtractor $extractor;

    public readonly BearerAuthenticator $authenticator;

    public readonly ScopePermissionRegistry $registry;

    /**
     * @param list<list<array<string, mixed>>> $keySets JWKS documents the fetcher will
     *        hand out, in order. The LAST one repeats indefinitely, which is what makes
     *        "the key arrived between two fetches" expressible without a live IdP.
     */
    public function __construct(
        array $keySets = [],
        ?OidcClientConfig $config = null,
        ?DfcReleaseConfig $release = null,
        ?TestClock $clock = null,
        ?OidcEndpoints $endpoints = null
    ) {
        $this->clock = $clock ?? new TestClock();
        $this->endpoints = $endpoints ?? JwtTestSupport::endpoints();
        $this->config = $config ?? JwtTestSupport::config();
        $this->registry = ScopePermissionRegistry::standard();

        $this->fetcher = new ScriptedJwksFetcher($keySets);

        $this->jwks = new JwksCache(
            $this->fetcher,
            $this->clock,
            $this->endpoints->jwksUri(),
            JwksCache::MIN_REFRESH_COOLDOWN_SECONDS,
            3600
        );

        $this->validator = new AccessTokenValidator(
            new LocalJwtDecoder(),
            $this->jwks,
            $this->endpoints,
            $this->config,
            $this->clock
        );

        $release ??= self::releaseConfig();

        $this->extractor = new BearerTokenExtractor($release);
        $this->authenticator = new BearerAuthenticator(
            $this->extractor,
            $this->validator,
            $this->registry
        );
    }

    /**
     * The DFC release config the harness authenticates against.
     *
     * Reuses the SHARED fixture descriptor rather than duplicating one: the challenge
     * realm must be an absolute https URI, which the identity suite's fixture base
     * satisfies, and two release descriptors in one test suite are two things to keep
     * in sync when the version is bumped.
     */
    public static function releaseConfig(): DfcReleaseConfig
    {
        return DfcReleaseConfig::fromDescriptorFile(
            __DIR__ . '/../../fixtures/dfc-release.yaml',
            ['platform_base_uri' => 'https://platform.example/dfc/v2']
        );
    }

    /**
     * One key set holding one signing key.
     *
     * The extra nesting is the point: a JWKS document is `{"keys": [...]}`, so a key
     * SET is a list of key sets. Returning a bare list of JWKs would be one document
     * too few, and the fetcher would iterate a JWK's members as if they were keys.
     *
     * @param array<string, string> $overrides
     *
     * @return list<list<array<string, mixed>>> A single key set.
     */
    public static function oneSigningKey(string $kid, array $overrides = []): array
    {
        return [[JwtFactory::jwk($kid, $overrides)]];
    }

    /**
     * The common case: one harness, one signing key, everything else defaulted.
     *
     * @param array<string, mixed>|null         $claims  Overrides for the valid claim
     *                                                      set; applied by the returned
     *                                                      harness's {@see self::tokenFor()}.
     * @param OidcClientConfig|null             $config
     * @param list<list<array<string, mixed>>> $keySets Scripted key sets.
     */
    public static function build(
        string $kid,
        ?array $claims = null,
        ?OidcClientConfig $config = null,
        ?array $keySets = null
    ): self {
        return new self(
            $keySets ?? self::oneSigningKey($kid),
            $config,
            null,
            null,
            null
        );
    }
}
